FROM python:3.9.2

ENV DASH_DEBUG_MODE False
ENV DASH_AUTH_MODE True

WORKDIR /app
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . /app


EXPOSE 8819

CMD ["gunicorn", "-b", "0.0.0.0:8819", "--reload", "eau2c2_dashcore:server","--timeout 600" ]
